name: Build Docker - Server

on:
  push:
    paths:
      - 'server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
      - name: Docker Build & Push
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server:$timestamp -f server/Dockerfile ./server
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/server:$timestamp ${{ secrets.DOCKERHUB_USERNAME }}/server:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:$timestamp
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:latest

