name: Build Docker

on:
  push:
    branches:
      - master  
  pull_request:
    paths:
      - 'docker/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
      - name: Docker Build & Push
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/all-spark-notebook:$timestamp -f docker/jupyter-notebook/Dockerfile.notebook ./docker/jupyter-notebook 
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/all-spark-notebook:$timestamp ${{ secrets.DOCKERHUB_USERNAME }}/all-spark-notebook:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/all-spark-notebook:$timestamp
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/all-spark-notebook:latest

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spark-history-server:$timestamp -f docker/spark-history-server/Dockerfile ./docker/spark-history-server
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/spark-history-server:$timestamp ${{ secrets.DOCKERHUB_USERNAME }}/spark-history-server:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spark-history-server:$timestamp
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spark-history-server:latest
