name: Integration Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: server
          POSTGRES_PASSWORD: password-server
          POSTGRES_DB: server_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      notebook:
        image: wenyixu101/notebook:latest
        env:
          JUPYTER_ENABLE_LAB: "no"
        ports:
          - "8888:8888"
        options: --health-cmd "curl -f http://localhost:8888 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
        
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: server

      - name: Run tests
        run: |
          python -m unittest discover tests
        working-directory: server
        env:
          ENV: integration